### ISSUE TITLE
Add scss-lint and a pre-push hook to lint all sass

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/pimp-my-cause-django#7]
- Install and configure for this project SCSS Linter with it's normal defaults,
- Add the linter to package json and update the README on how to install it. Mention about editorconfig and getting the linter to work in the Editor
- Setup a pre-push git hook in package json to run the linter
-Test and make sure linter runs every time user tries to push code on a branch

**Comment by elischutze** [comment]
Is this still valid?

**Comment by lili2311** [comment]
I would like to add it yeah, it will remove some of the work reviewing as it will enforce a style.

**Comment by elischutze** [comment]
Perf 👍
