### ISSUE TITLE
Bug testing the homepage

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/pimp-my-cause-django#72]
Please manually test the current homepage deployed to heroku: https://staging-pimpmycause.herokuapp.com/

Look for and note down on this ticket any of the below issues:
- Broken links
- Buttons not working as expected
- Styles or layout issues (things behave unexpected when resizing the browser)
- Test in a few different browsers: Chrome, Safari, Firefox and IE if possible
- Test on mobile if possible as well

**Comment by OyaOrhan** [comment]
- on the NavBar "Find a Cause" and "Find a Marketer" links don't work
- Although I signed in, and follow "join us" and click "continue" button, it brings me registration form again.
- On the grapfic animation these links don't work: "News", "Find a Cause" and "Find a Marketer"
- at the bottom side of the homepage in the "have you seen" section:
  * How it works link doesn't work
  * "Challenges" link goes to top
- I filled the contact us form. It asked me to confirm my email. I signed it already. Best way may be getting my thoughts with the form without asking my email, phone, name and surname again. And I didn't receive a confirmation mail. When I click "Resend confirmation email?" link, I got a error: "550 5.1.1 Recipient not found."
