### ISSUE TITLE
QA ONLY: Image preview

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/pimp-my-cause-django#74]
When a user select a new image file it should loaded instead of the current profile image to preview what it looks like before save is clicked.

If user did not click save the new image is discarded.

To test:

Please register an account on Pimp My Cause https://staging-pimpmycause.herokuapp.com/
Then follow the email instructions and Fill Out your profile, when choosing an image try replacing it after save.

**Comment by mangogeek** [comment]
Uploaded portfolio image:
![uploaded portfolio pic](https://cloud.githubusercontent.com/assets/19766208/24322633/4cb963b4-1160-11e7-910f-1fb6dd1320f7.png)

Try to save new portfolio pic and asked to fill in every other field:
![uploaded portfolio pic](https://cloud.githubusercontent.com/assets/19766208/24322653/afa04ce0-1160-11e7-94ba-d76005b1ce27.png)
