### ISSUE TITLE
Don't allow logged in users to go to reset password page, just redirect to homepage or profile.

### ISSUE THREAD

**Issue by yanabar** [womenhackfornonprofits/pimp-my-cause-django#79]
Go to https://staging-pimpmycause.herokuapp.com/ try to register (if you are registered just log back in) and try to access the link https://staging-pimpmycause.herokuapp.com/accounts/password/reset/ and send a screen shot of what you get.

**Comment by mangogeek** [comment]
![reset](https://cloud.githubusercontent.com/assets/19766208/24322441/6e3156fe-115c-11e7-8942-cd257815aca5.jpg)
